"""add notifications and form_graph_diffs tables

Revision ID: 3d930491de06
Revises: 56950875d7f4
Create Date: 2026-03-19 14:49:33.345899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d930491de06'
down_revision: Union[str, Sequence[str], None] = '56950875d7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_graph_diffs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_graph_id', sa.Uuid(), nullable=False),
    sa.Column('old_version', sa.Integer(), nullable=False),
    sa.Column('new_version', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False, comment='none | cosmetic | structural | breaking'),
    sa.Column('diff_data', sa.JSON(), nullable=True, comment='Full diff result as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_graph_id'], ['form_graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_graph_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False, comment='form_outdated | form_broken | form_degraded | exploration_complete | exploration_failed'),
    sa.Column('title_de', sa.String(length=500), nullable=False),
    sa.Column('message_de', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_graph_id'], ['form_graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('form_graph_diffs')
    # ### end Alembic commands ###
