"""create form_graphs table

Revision ID: bb942b9c448c
Revises: 
Create Date: 2026-03-19 11:29:08.132869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb942b9c448c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_graphs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.String(length=100), nullable=True, comment='External ID like KFAS_CQ00171'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=True, comment='Full form graph: steps, fields, sections, conditional logic'),
    sa.Column('mcp_tool_spec', sa.JSON(), nullable=True, comment='Generated MCP tool definition'),
    sa.Column('explored_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('automation_notes', sa.JSON(), nullable=True, comment='Platform quirks, login requirements, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_graphs')
    # ### end Alembic commands ###
