"""create exploration_jobs table

Revision ID: e0329aee4f14
Revises: bb942b9c448c
Create Date: 2026-03-19 12:03:34.876159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0329aee4f14'
down_revision: Union[str, Sequence[str], None] = 'bb942b9c448c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploration_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_graph_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_log', sa.JSON(), nullable=True, comment='Array of {step, message, timestamp}'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_graph_id'], ['form_graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exploration_jobs')
    # ### end Alembic commands ###
